classDiagram
    goker ..> Table
    Table ..> Player
    Table ..> Pot
    Table ..> Dealer
    Pot ..> SidePot
    Dealer ..> Deck
    Deck ..> Card

    class goker {
        +OpenTable()$ Table
    }

    class Table {
        -string uuid
        -List~Player~ players
        -Pot pot
        -Dealer dealer

        +UUID() string
        +PlayerJoin(playerUuid string)
        +PlayerLeave(playerUuid string)
        +Close()
    }

    class Player {
        -string uuid
        -int stack
        -Array~Card~ holdCards
        -int currentBet

        +UUID() string
        +Stack() int
        +HoldCards() Array~Card~

        +Bet(chips int) error
        +FinishHand(earnedChips int)
    }

    class Pot {
        -int value
        -List~*Player~ eligiblePlayers

        ~collectChips()
        ~rewardChips(*Player player)

        +Value() int
        +EligiblePlayers() Array~string~
        +PlayerBets() Map~string_int~
        +SidePots() Array~SidePot~
    }

    class Dealer {
        -Deck deck
    }

    class Deck {
        -dealtCards List~Card~
        -remainingCards List~Card~

        +DealtCards() List~Card~
        +Deal(cardsNum int) List~Card~
    }

    class Card {
        -Rank rank
        -Suit suit

        +Rank() Rank
        +Suit() Suit
    }
