classDiagram
    Table ..> Pot
    Table ..> Dealer
    Table ..> Player
    Pot ..> SidePot

    class Table {
        +NewTable()$ Table

        +UUID() string
        +Close()
    }

    class Pot {
        ~bet(string playerUuid, int chips)
        ~collectChips(Array~*Player~ players)
        ~rewardChips(*Player player)

        +Value() int
        +PlayerBets() Map~string_int~
        +SidePots() Array~SidePot~
    }

    class SidePot {
        +EligiblePlayers() Array~string~
        +Value() int
    }

    class Dealer {
    }

    class Player {
        +NewPlayer(string uuid)$ Player

        +UUID() string
        +JoinTable(*Table table)
        +Stack() int
        +LeaveTable()
    }

