sequenceDiagram
    participant Player
    participant Pot
    participant Dealer
    participant Table

    Player->>+Table: Join table

    activate Table
    alt max Players exceeded
        Table-->>Player: Max players exceeded
    else
        Table-->>Player: Seat position
    end
    deactivate Table

    alt is first Player
        Table->>Table: Wait for more Players
    else 
        Table->>Table: Wait for next Dealer
    end

    Table->>Dealer: Start new hand
    Note over Player,Table: See "Dealer flow"

    Player->>+Table: Leave table
    Table->>-Table: Check and update dealer button

