sequenceDiagram
    participant Player
    participant Pot
    participant Dealer
    participant Table

    Dealer->>Player: Winner
    Dealer->>Pot: Reward chips
    Pot->>Player: Reward chips
    Dealer->>+Player: Recall hold cards
    Player-->>-Dealer: Hold cards
    Dealer->>Table: Hand ended

